version: '3.6'
services:
  kibana:
    container_name: kibana
    image: kibana:6.5.4
    environment:
      SERVER_NAME: 172.50.0.34
      ELASTICSEARCH_URL: http://172.50.0.33:9200
    networks:
      esnet:
        ipv4_address: 172.50.0.34
  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /sakuraus/go/src/learn/crawler/docker/esdata1:/usr/share/elasticsearch/data
      - /sakuraus/go/src/learn/crawler/docker/esconf:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    networks:
      esnet:
        ipv4_address: 172.50.0.33      
    tty: true
    command: [./bin/elasticsearch]
networks:
  esnet:
    external:
      name: docker_redis-cluster-net
#  docker run -it docker.elastic.co/elasticsearch/elasticsearch:5.6.9 bash
#  进入镜像 修改权限
